### ISSUE TITLE
missing file error if I retry the script after deleting the output

### ISSUE THREAD

**Issue by nitaro** [StateArchivesOfNorthCarolina/DarcMailCLI#3]
Looks like if I run it and then want to re-do by deleting the "data" and "eaxs_xml" folders then I will get the error below unless I delete "basic_logger.yml".

So maybe the script should catch that error and message the user, or maybe the YAML file should get overwritten each time (or timestamped)?

I have to look into it further, but those are just the thoughts for now.

`Traceback (most recent call last):
  File "C:\Python36\lib\logging\config.py", line 558, in configure
    handler = self.configure_handler(handlers[name])
  File "C:\Python36\lib\logging\config.py", line 731, in configure_handler
    result = factory(**kwargs)
  File "C:\Python36\lib\logging\handlers.py", line 150, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "C:\Python36\lib\logging\handlers.py", line 57, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "C:\Python36\lib\logging\__init__.py", line 1025, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Python36\lib\logging\__init__.py", line 1054, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\TOMES\\TESTS\\StanfordSpaceTests\\mbox\\.zach.ambrose-CA1@nc.gov\\.zach.ambrose-CA1@nc.gov (MainArchive)\\Top of Information Store\\Inbox\\eaxs_xml\\error.log'`

**Comment by jmgibson71** [comment]
Nitin, could you post the params and arguments you are passing when you get this error.

**Comment by nitaro** [comment]
I was able to get this earlier today using:
```
py -3 .\DarcMailCLI.py -a nitin -d 'D:\TOMES\TESTS\20170220_darcmail_test\mbox\In
box\'
```
but I'm now also getting other errors.
I need to back-track on this and start over and get you a good report on each step and the errors.
I was not getting errors using a simple MBOX file (i.e. my Outlook emails).
